version: 0.2
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y rsync
      - gem install jekyll
  build:
    commands:
      - cd 2011 && jekyll build && cd ..
      - mkdir build
      - rsync -r 2005-2010/ build/
      - rsync -r 2011/_site/ build/2011/
artifacts:
  files:
    - 'build/*'
  name: blog-archive-$(date +%Y%m%d)
