version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/work

    steps:
      - checkout
      - run: sudo apt-get install -qq -y rsync

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - deps-fallback

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
      - run: npm run generate
      - run: rsync -rv 2005-2010/ dist/
      - persist_to_workspace:
          root: ~/work/dist
          paths:
            - ./*
  deploy:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/work
    steps:
      - run: sudo apt-get install -qq -y s3cmd python-pip libpython-dev
      - run: sudo pip install -q awscli --upgrade
      - attach_workspace:
          at: ~/work/dist
      - run: s3cmd sync --acl-public --no-mime-magic --guess-mime-type --default-mime-type=text/html --cf-invalidate dist/ s3://blog.8-p.info-2017/
      - run:
          name: Invalidate /*
          command: aws cloudfront create-invalidation --distribution-id EZLOTA1EGTZ45 --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
