version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/work

    steps:
      - checkout
      - run: sudo apt-get install -qq -y ruby rsync
      - run: mkdir -p v2/data/posts/
      - run: ruby prepare-data.rb > v2/data/posts/all.json
      - run:
          name: "Install Hugo"
          command: ls -l hugo || wget -O - https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz | tar zxvf -
      - run: cd v2 && ../hugo
      - run: cp -r v2/public dist
      - run: rsync -rv 2005-2010/ dist/
      - persist_to_workspace:
          root: ~/work/dist
          paths:
            - ./*
  deploy:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/work
    steps:
      - run: sudo apt-get install -qq -y s3cmd python-pip libpython-dev
      - run: sudo pip install -q awscli --upgrade
      - attach_workspace:
          at: ~/work/dist
      - run: s3cmd sync --acl-public --no-mime-magic --guess-mime-type --default-mime-type=text/html --cf-invalidate dist/ s3://blog.8-p.info-2017/
      - run:
          name: Invalidate /*
          command: aws cloudfront create-invalidation --distribution-id EZLOTA1EGTZ45 --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
