version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/work

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - deps-fallback

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
      - run: npm run generate
      - persist_to_workspace:
          root: ~/work/dist
          paths:
            - ./*
  deploy:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: ~/work/dist
      - run:
          name: "Install awscli and s3cmd"
          command: sudo apt-get install -qq -y awscli s3cmd
      - run: s3cmd sync --acl-public --guess-mime-type --cf-invalidate . s3://blog.8-p.info-2017/
      - run:
          name: Invalidate /*
          command: aws cloudfront create-invalidation --distribution-id EZLOTA1EGTZ45 --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
